### ISSUE TITLE
Как добавить кириллицу?

### ISSUE THREAD

**Issue by AlexeyJW** [sidebase/nuxt-pdf#15]
### Ask your question

Как добавить кириллицу?
Как получить из '#imports'  объект jsPDF?

**Comment by Johongirmirzo** [comment]
I also want to know know how could we create pdf not only latin but also in cyrillic language?

**Comment by zoey-kaiser** [comment]
Hi everyone, please check out #10 for more information on to to:
- Currently do this
- My plan to improve DX in the future to make this even easier!
