### ISSUE TITLE
 [unimport] failed to find "exportToPDF" imported from "#imports"

### ISSUE THREAD

**Issue by AsirMahmud** [sidebase/nuxt-pdf#18]
### Ask your question

when I use this import { exportToPDF } from '#imports'; 
it does not work I have install the package but still does not work
what can I do??

**Comment by Jorgagu** [comment]
Hi @AsirMahmud, have you correctly put your module in your nuxt config like it's say in the quick start documentation here ?https://sidebase.io/nuxt-pdf/getting-started/quick-start

**Comment by zoey-kaiser** [comment]
Hi @AsirMahmud 👋 

As the module gets auto-imported but Nuxt, you should be able to just use `exportToPDF` inside your project, without any imports. This import is only needed inside the playground, as it gets compiled diffrently. 

As @Jorgagu noted, please check that you have followed the installation guide. You can view this here: 
https://sidebase.io/nuxt-pdf/getting-started/installation
https://sidebase.io/nuxt-pdf/getting-started/quick-start
