### ISSUE TITLE
getPageHeight does not existe

### ISSUE THREAD

**Issue by TartanLeGrand** [sidebase/nuxt-pdf#21]
### Environment

- Operating System: Windows_NT
- Node Version:     v19.8.1
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      app, chatwoot, colorMode, cookieControl, css, dayjs, devtools, googleFonts, i18n, modules, runtimeConfig, site, sitemap, srcDir, telemetry, ui, vite, vue
- Runtime Modules:  @nuxt/ui@2.11.1, @sidebase/nuxt-pdf@0.1.2, @nuxtjs/i18n@8.0.0-rc.5, nuxt-headlessui@1.1.4, nuxt-simple-sitemap@3.4.1, nuxt-simple-robots@3.1.9, nuxt-schema-org@3.2.1, nuxt-og-image@2.2.4, @nuxt/image@1.1.0, @nuxtseo/module@2.0.0-beta.45, @pinia/nuxt@0.5.1, @dargmuesli/nuxt-cookie-control@6.5.3, dayjs-nuxt@2.1.9, @nuxtjs/partytown@1.3.0, @productdevbook/chatwoot@1.4.0, @nuxtjs/google-fonts@3.1.3
- Build Modules:    -

### Reproduction

https://sidebase.io/nuxt-pdf/getting-started/composables#htmltopdf

### Describe the bug

 On the const pdfHeight = pdf.getPageHeight()
 
Property getPageHeight does not exist on type jsPDF

**Comment by zoey-kaiser** [comment]
Hi, yes I have noticed this. AFAIK they updated this to be the following in a new version. Their docs are a bit outdated when it comes to this:

```ts
pdf.pageSize.getHeight()
pdf.pageSize.getWidth()
```

See https://github.com/parallax/jsPDF/issues/1888
