### ISSUE TITLE
PDF-Export of non rendered components

### ISSUE THREAD

**Issue by hennihaus** [sidebase/nuxt-pdf#9]
### Ask your question

Hello together,

is there a possibility to export a component to pdf without rendering this component in DOM/Display? Maybe this is a nice feature for this nuxt module.

With best regards
Henni

**Comment by zoey-kaiser** [comment]
> is there a possibility to export a component to pdf without rendering this component in DOM/Display? Maybe this is a nice feature for this nuxt module.

Currently there is not. The "rendering" works by taking a snapshot of the html displayed on the client side, so it needs to be rendered at some point to determine what the PDF looks like. 

I am currently working on implementing a server side solution in #7, which would allow you to render it via the server and not display it at all to the end user!

I would recommend you follow the progress on that issue and raise any questions or concerns there. Thanks for your support and I hope to be able to ship the feature soon!
